import { ChevronLeft, ChevronRight } from '@mui/icons-material'
import { Button, Grid, Tooltip, Typography } from '@mui/material'
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import { useRouter } from 'next/router'
import { useState } from 'react'
import styles from '../styles/Home.module.css'
import { getEmojiNameByEmoji } from '../utility/emojiMethods'
import Footer from './Footer'
import { websiteName } from './Globals'
import ImageViewer from './ImageViewer'
import TopBanner from './TopBanner'

export default function EmojiPage({ emoji, pictures, prevEmoji, nextEmoji }) {
  const router = useRouter();
  const [fullscreenPhotoIndex, setFullscreenPhotoIndex] = useState(null);

  function renderNavigationButton(emoji, isNext) {
    return (
      <Link href={`/emoji/${emoji}`}>
        <Grid container style={{ width: "auto", cursor: "pointer" }} alignItems="center" spacing={1}>
          {isNext ? "" :
            <Grid item>
              <ChevronLeft style={{ fontSize: 24, marginTop: 4 }} />
            </Grid>
          }
          <Grid item>
            <Tooltip title={getEmojiNameByEmoji(emoji)}>
              <Typography style={{ fontSize: 32 }}>
                {emoji}
              </Typography>
            </Tooltip>
          </Grid>
          {isNext ?
            <Grid item>
              <ChevronRight style={{ fontSize: 24, marginTop: 4 }} />
            </Grid>
            : ""}
        </Grid>
      </Link>
    );
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>{`${websiteName} - ${emoji}`}</title>
        <meta name="description" content="A gallery of DallE2 generations for single emoji prompts 💃🏻 🌠 🐱 🚀 🤩" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>

        <TopBanner showBack showTitle />

        <Grid container justifyContent="space-between" alignItems="center" style={{ marginBottom: 16 }}>

          <Grid item>
            {prevEmoji ?
              <EmojiNavigationButton emoji={prevEmoji} isNext={false} />
              : ""
            }
          </Grid>

          <Grid item>
            {/* Title */}
            <Tooltip title={getEmojiNameByEmoji(emoji)}>
              <Typography component="h1" className={styles.title} style={{ fontSize: 88, lineHeight: 1.0 }}>
                {emoji}
              </Typography>
            </Tooltip>
          </Grid>

          <Grid item>
            {nextEmoji ?
              <EmojiNavigationButton emoji={nextEmoji} isNext />
              : ""
            }
          </Grid>

        </Grid>

        <Typography align="center" style={{ fontWeight: 500, fontSize: 16, color: "darkgray", marginBottom: 16 }}>
          The emoji above was fed into <span style={{ textDecoration: "none" }}><Link href="https://openai.com/dall-e-2/">DallE2</Link></span> as the sole prompt.<br />
          These are the resulting images
        </Typography>

        <Grid container spacing={1} justifyContent="center" alignItems="center">
          {pictures.map((emojiPicture, pictureIndex) =>
            <Grid item key={pictureIndex} onClick={() => setFullscreenPhotoIndex(pictureIndex)} style={{ cursor: "pointer" }}>
              <Image src={emojiPicture} width={256} height={256} alt={`An image generated by DallE2 for the prompt ${emoji}`}/>
            </Grid>
          )}
        </Grid>
        
        <Typography align="center" style={{ fontWeight: 500, fontSize: 12, color: "darkgray", marginTop: 8 }}>
          * No Cherry Picking Disclaimer: <em>All images generated by DallE2 to the supplied prompts were uploaded to the website without filtering or selection</em>
          
        </Typography>

      </main>

      <ImageViewer
        photos={pictures || []}
        fullscreenPhotoIndex={fullscreenPhotoIndex}
        setFullscreenPhotoIndex={setFullscreenPhotoIndex}
      />

      <Footer />
    </div>
  )
}

function EmojiNavigationButton({ emoji, isNext }) {
  const [isHovered, setIsHovered] = useState(false);

  return (
    <Link href={`/emoji/${emoji}`}>
      <Grid container alignItems="center" spacing={1}
        style={{
          width: "auto", 
          cursor: "pointer", 
          transition: "transform 0.2s ease",
          transform: `scale(${isHovered ? 1.5 : 1})`
        }}
        onMouseEnter={() => setIsHovered(true)}
        onMouseLeave={() => setIsHovered(false)}>
        {isNext ? "" :
          <Grid item>
            <ChevronLeft style={{ fontSize: 24, marginTop: 4 }} />
          </Grid>
        }
        <Grid item>
          <Tooltip title={getEmojiNameByEmoji(emoji)}>
            <Typography style={{
              fontSize: 32,
            }}>
              {emoji}
            </Typography>
          </Tooltip>
        </Grid>
        {isNext ?
          <Grid item>
            <ChevronRight style={{ fontSize: 24, marginTop: 4 }} />
          </Grid>
          : ""}
      </Grid>
    </Link>
  );
}